sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: IKhkz5brlSK8coqCJEhBiyuZoiBQpS
    access-key-id: LTAI5tEZEt2n4EaLSXNS8gzz
    bucket-name: java-ai32694
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx4d0e222feafde2e0
    secret: ec8bb8621c0e6edb80baf74d29e24cd2